### ISSUE TITLE
ANT App Tools Project

### ISSUE THREAD

**Issue by RedCarrottt** [SKKU-ESLAB/ANT#123]
There are many issue related to new tools for ANT application management or development.

I arrange those issues in this issue.

- [x] <del>**App Package Maker Tool** (#122)</del> (not required in single-app architecture)
  * Command line based
  * Functions: Make app package
- [x] <del>**App Manager Tool** (#108)</del>  (not required in single-app architecture)
  * Command line based
  * Functions: Install app, remove app, inquire installed app list, inquire running app's state
  * *Temporary alternative: test system app (PR #125)*
- [x] **App Editor** (#109) (PR #138)
  * Web-based
  * Functions: edit app code, make app package, install/run the code, view app's console log
- [x] <del>**App Market** (#117)</del>  (not required in single-app architecture)
  * Web-based
  * Functions: download apps

**Comment by RedCarrottt** [comment]
Since all of the items are completed, I close this issue.
