### ISSUE TITLE
Push every build processes into cmake/make

### ISSUE THREAD

**Issue by RedCarrottt** [SKKU-ESLAB/ANT#126]
Currently, ANT framework build process is too complicated.

Too many steps and tools are required to build.

* **Current Build Process**
  1. Install prerequisites (Use ```install-deps-*.sh```)
  2. Build sensor driver (Use ```cmake```, ```make```, ```cp```)
  3. Build main code (Use ```cmake```, ```make```) with target board option
  4. Install (Use ```install.sh```)

We need to simplify the build process; less steps and less tools.

* **New Build Process**
  1. Install prerequisites
      * ```install-deps.sh {board name}```
  2. Build config (target board option, framework/API on/off setting, etc.)
      * ```./menuconfig.py```
  3. Cmake
      * ```mkdir build & cd build```
      * ```cmake ..```
  4. Build (both main & sensor driver code)
      * ```make -j4```
  5. Install
      * ```sudo make install```

**Comment by RedCarrottt** [comment]
# To-do
- [ ] Framework config
  - [ ] Remove target board option via command line arguments
  - [ ] Remove additional command for building sensor driver
- [ ] Install by ```cmake```
- [ ] Install prerequisites by ```cmake```
