### ISSUE TITLE
ANT issues summary

### ISSUE THREAD

**Issue by LeeHayun** [SKKU-ESLAB/ANT#250]
Currently, many issues are registered, but most of them are neglected for a long time.
So, I summarized the old issues.

# Maintenance
- [ ] Unified Logging System (#65)
- [ ] Enhancing build processes (#126)
- [ ] Debug mode (#132)
- [ ] JS runtime type setting (#139)
- [ ] Separating a branch for Classic ANT and Launching ANT Lite (#168)

# Cloud
- [ ] Google Cloud Plug-in needs a test (#93)
- [ ] Server-side example code for Google Cloud (#94)
- [ ] Merge ANT Lite into the configurable build system (#187)
- [ ] Support for Cortex-M MCUs (#189)
- [ ] Add Inter-thread Binding Layer (IBL) (#194)
- [ ] ANT API Python-version (#208)
- [ ] Function to acquire device name in ANT runtime API (#229)
- [ ] Pad support in stream API (#231)
- [ ] Unstable start when ill-coded app is installed (#240)

# Gateway
- [ ] Merging Gateway Software (#101)

# Network
- [ ] Merging Selective Connection (#106)
- [ ] Upgrade bluez library version (#107)

# Stream
- [ ] Sensor driver documentation (#112)
- [ ] Replace sensor framework with GStreamer elements (#145)
- [ ] Porting NNStreamer to Raspbian (#170)

# Companion
- [ ] Remote UI library for third-party android apps (#114)

# ML
- [ ] SegFault occurs when restarting ML API example (#175)
- [ ] ML APIs to specify pre-processing of ML models (#178)
- [ ] ML API example makes black frame output on Jetson TX2 (#179)
- [ ] ML API's image segmentation support (#242)

# App editor
- [ ] App status monitoring on app editor (#159)
- [ ] Decoupling ANT Runtime and ANT App into seperated processes (#176)
- [ ] Upgrade app editor (#228)

Please comment on whether or not to address these issues and when and how to address them.

First of all, I close all related issued.
When necessary, I hope to reopen the issue and work on it.

**Comment by LeeHayun** [comment]
This issue has been inactive for a long time and no longer reflects our current priorities. I'm closing it for now. If you believe this matter should be revisited or if you have new insights, please feel free to open a new issue so we can take a fresh look. Thank you for your contributions.
