### ISSUE TITLE
Divide ANT API by JS part and native part

### ISSUE THREAD

**Issue by RedCarrottt** [SKKU-ESLAB/ANT#79]
Currently, ANT API is composed of only C++ native code.
Functions in the native code are directly bound to JS function calls.

All the JS API functions should have code for **exception handling** and **argument type checking**.
It is because JavaScript is dynamic type language and its functions do not restrict their arguments.

As now, exception handling and argument type checking is implemented in native code.
Implementing those in C++ is very inefficient and not good for code readability.

Accordingly, I propose to divide ANT API by JS part and native part.
* **JS Part**: function prototype, exception handling, argument type checking, making JSON string
* **Native Part**: dbus IPC, libuv async handling

**Comment by RedCarrottt** [comment]
It's weakly related to Issue #22.

**Comment by RedCarrottt** [comment]
# To-do
- [ ] **Resource API**
- [ ] **Remote UI API** (#104)
- [ ] **App API**
- [ ] **Camera API**
- [ ] **Sensor API**
- [ ] **Machine Learning API**
- [x] **Cloud API & Google Cloud Plug-in**: It is already JS-only API.

**Comment by RedCarrottt** [comment]
According to PR #125, Dividing JS API for Remote UI API is implemented.

**Comment by RedCarrottt** [comment]
With #136, this issue can be resolved, so I merge this issue to #136.
