### ISSUE TITLE
Cloud API and Google Cloud Plug-in Proposal

### ISSUE THREAD

**Issue by RedCarrottt** [SKKU-ESLAB/ANT#80]
I propose Cloud API and Google Cloud Plug-in.

Cloud API covers basic function calls for MQTT Pub/Sub.

Google Cloud Plug-in covers authentication on connection time and name convention handling in MQTT token, subscription, or project name.

Those new modules can be used for connecting ANT sensor framework or inference framework to Google Cloud.

Sensor data or video frame from ANT device can be stored to Google Cloud's "Cloud BigTable" or used to analysis using "Cloud ML".

# To-do
- [x] Skeleton for Cloud API
- [x] Cloud API
- [x] Google Cloud Plug-in
  - [x] Token refresh
  - [x] Reset callbacks on token refresh 
- [x] Test

**Comment by RedCarrottt** [comment]
# Example code for Cloud API
```
var ant_api_dir = process.env.ANT_BIN_DIR + "/api/";
var cloudAPI = require(ant_api_dir + "cloud-api");

// clientId, username, password should be set before this call.
// Cloud API does not include authentication process.
// You should make your own authentication process if you use Cloud API.
var connection = cloudAPI.connectMQTT("mqtt.googleapis.com", 8883, clientId, username, password);

// Assume that sensorData has JSON object of sensor data
connection.publish("/devices/antDevice/events", JSON.stringify(sensorData));

connection.subscribe("/devices/antDevice/config", function(topic, message) {
  console.log("Got message for config: " + message);
});

setTimeout(function() {
  // Close connection after 1 hour.
  connection.close();
}, 3600);
```

# Example code for Google Cloud Plug-in
```
var ant_api_dir = process.env.ANT_BIN_DIR + "/api/";
var gcloud = require(ant_api_dir + "cloud-api/google-cloud-plugin");

// This function call connects Google Cloud with authentication, and refresh secure token periodically.
var connection = gcloud.connectSecure({
  projectId: "ant-project",
  privateKeyFile = "rsa_private.pem",
  registryId = "ant-device",
  deviceId = "home-sensor-puck"
});

// Assume that sensorData has JSON object of sensor data
connection.publishEvents(JSON.stringify(sensorData));

connection.subscribeConfig(function(message) {
  console.log("Got message for config: " + message);
});

setTimeout(function() {
  // Close connection after 1 hour.
  connection.close();
}, 3600);
```

**Comment by RedCarrottt** [comment]
This job is completed and merged to mainline last year. Therefore I close this issue.
