### ISSUE TITLE
API Documentation Update Required

### ISSUE THREAD

**Issue by RedCarrottt** [SKKU-ESLAB/ANT#95]
We've made or updated many APIs in ANT framework 2.0.
However, ANT Project's Wiki page is not updated yet.

# To-do
- [ ] Machine Learning API (updated for DNN/CNN's InferenceOption)
- [ ] Remote UI API
- [ ] Cloud API
- [ ] Sensor Database API (New)

**Comment by RedCarrottt** [comment]
ANT APIs are changed to have simpler functions, as mentiond in PR #137.

Therefore, this task is not required. I close this issue.
